name: golangci-lint
on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install libx11-dev for clipboard support
        run: sudo apt install libx11-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
          args: --disable=errcheck
